"""added Follow and User relationship

Revision ID: 6586a0076ef3
Revises: d660ea4d8940
Create Date: 2024-09-14 21:04:25.246789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6586a0076ef3'
down_revision: Union[str, None] = 'd660ea4d8940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'follow', 'user', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'follow', 'user', ['follower_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    # ### end Alembic commands ###
