"""added Tweet and Media relationship

Revision ID: d660ea4d8940
Revises: 715d94d05320
Create Date: 2024-09-14 21:01:58.769706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd660ea4d8940'
down_revision: Union[str, None] = '715d94d05320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'media', 'tweet', ['tweet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    # ### end Alembic commands ###
